config/routes.rb
Rails.application.routes.draw do

  mount ShopCart::Engine, at: '/cart', as: 'shop_cart'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks"}
  root 'books#home'
  resources :categories, only: [:show]
  resources :order_steps, only: [:show, :update]

  resources :books, only: [:index, :show] do
    get 'home',on: :collection
    resources :ratings, only: [:create, :new]
  end

  resource :customer, only: [:show,:update,:destroy]

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
 include AddressSaver

  has_many  :orders, class_name: 'ShopCart::Order'
  has_many  :ratings
  has_many  :addresses
 # has_many  :credit_cards

  belongs_to :billing_address, class_name: "Address"
  belongs_to :shipping_address, class_name: "Address"


  validates :email,presence: true
  validates :email, uniqueness: { case_sensitive: false }


  def admin?
    self.admin
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |customer|
      customer.email = auth.info.email
      customer.password = Devise.friendly_token[0, 20]
      customer.first_name = auth.info.first_name
      customer.last_name = auth.info.last_name
      customer.provider = auth.provider
      customer.uid = auth.uid
    end
  end

  def order_in_progress
    self.orders.find_or_create_by(state: 'in progress')
  end

  def last_orders
    self.orders.already_completed.order(state: :asc, completed_date: :desc).first
  end

  def all_orders
    self.orders.already_completed.order(state: :asc, completed_date: :desc)
  end

end

app/controllers/customers/confirmations_controller.rb
class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @customer = Customer.from_omniauth(request.env["omniauth.auth"])

    if @customer.persisted?
      sign_in_and_redirect @customer, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_customer_registration_url
    end
  end



  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
class Customers::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
class Customers::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/customers/unlocks_controller.rb
class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  authorize_resource
  include CustomerSettings
  before_action  :set_data

  def show
    @billing_address  ||= @customer.billing_address  || Address.new
    @shipping_address ||= @customer.shipping_address || Address.new
    render :show
  end

  def update
    if @customer.update(customer_params)
      flash[:success] = "Your #{customer_params.keys.to_s.slice(2..-3)} was updated."
      redirect_to :back
    else
      show
    end
  end

  def destroy
    if params.has_key?(:remove_account_confirm)
      @customer.destroy
      redirect_to root_path
    else
      flash[:danger] = 'You should confirm your action!'
      redirect_to :action => "show"
    end
  end

  def set_data
    @customer = CustomersForm.new(current_customer)
  end

  def customer_params
    params.permit(
        shipping_address: [:first_name, :last_name, :address, :city, :country_id, :zipcode, :phone],
        billing_address:  [:first_name, :last_name, :address, :city, :country_id, :zipcode, :phone],
        email: [:email],
        password: [:current_password, :password, :password_confirmation])
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_address.html.erb
<%= hidden_field_tag(:type, type) %>
<div class="form-group">
  <%= text_field_tag(type+'_address[first_name]', address.first_name, :class => 'form-control', :placeholder => 'First name') %>
</div>
<div class="form-group">
  <%= text_field_tag(type+'_address[last_name]', address.last_name, :class => 'form-control', :placeholder => 'Last name') %>
</div>
<div class="form-group">
  <%= text_field_tag(type+'_address[address]', address.address, :class => 'form-control', :placeholder => 'Street address') %>
</div>
<div class="form-group">
  <%= text_field_tag(type+'_address[city]', address.city, :class => 'form-control', :placeholder => 'City') %>
</div>
<div class="form-group">
  <div class="input-group">
    <div class="input-group-addon">Country</div>
    <%= select_tag(type+'_address[country_id]', options_for_select(countries, address.country_id), :class => 'form-control')%>
  </div>
</div>
<div class="form-group">
  <%= text_field_tag(type+'_address[zipcode]', address.zipcode, :class => 'form-control', :placeholder => 'Zip code') %>
</div>
<div class="form-group">
  <%= text_field_tag(type+'_address[phone]', address.phone, :class => 'form-control', :placeholder => 'Phone number') %>
</div>

app/views/customers/_errors.html.erb
<% unless @errors[area.to_sym].nil? %>
   <ul>
     <% @errors[area.to_sym].each do |message| %>
        <li><%= message %></li>
     <% end %>
   </ul>
<% end %>

app/views/customers/edit.html.erb
<div class="settings clearfix">
  <h1>Settings</h1>
  <div class="row">
    <div class="col-md-6 col-lg-3 col-lg-offset-2">
      <h2>BILLING ADDRESS</h2>
      <%= form_tag(address_customer_path, :method => 'put') do %>
         <%= render partial: 'shared/errors', locals:{ entity: [@billing_address] }  %>
         <%= render 'address', type: 'billing', address: @billing_address %>
         <%= submit_tag('SAVE', :class => 'btn btn-default') %>


      <% end %>
    </div>
    <div class="col-md-6 col-lg-3 col-lg-offset-2">
      <h2>SHIPPING ADDRESS</h2>
      <%= form_tag(address_customer_path, :method => 'put') do %>
         <%= render partial: 'shared/errors', locals:{ entity: [@shipping_address] }  %>
         <%= render 'address', type: 'shipping', address: @shipping_address %>
         <%= submit_tag('SAVE', :class => 'btn btn-default') %>

      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-lg-3 col-lg-offset-2">
      <h2>E-MAIL</h2>
      <%= form_tag(email_customer_path, :method => 'put') do %>
         <%= render partial: 'shared/errors', locals:{ entity: [@customer] }  %>

         <div class="form-group">
           <%= email_field_tag('customer[email]', @customer.email, :class => 'form-control', :placeholder => 'Enter email')%>
         </div>
         <%= submit_tag('SAVE', :class => 'btn btn-default') %>
      <% end %>
    </div>
    <div class="col-md-6 col-lg-3 col-lg-offset-2">
      <h2>PASSWORD</h2>
      <%= form_tag(password_customer_path, :method => 'put', :autocomplete => 'off') do %>
         <%= render partial: 'shared/errors', locals:{ entity: [@customer] }  %>
         <div class="form-group">
           <%= label_tag('customer[current_password]', 'Current password')%>
           <%= password_field_tag('customer[current_password]', '', :class => 'form-control', :placeholder => 'Type current password') %>
         </div>
         <div class="form-group">
           <%= label_tag('customer[password]', 'New password')%>
           <%= password_field_tag('customer[password]', '', :class => 'form-control', :placeholder => 'Type new password') %>
         </div>
         <div class="form-group">
           <%= label_tag('customer[password_confirmation]', 'New password confirmation')%>
           <%= password_field_tag('customer[password_confirmation]', '', :class => 'form-control', :placeholder => 'Type new password confirmation') %>
         </div>
         <%= submit_tag('SAVE', :class => 'btn btn-default') %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-lg-offset-4">
      <h2>REMOVE ACCOUNT</h2>
      <%= form_tag(customer_path, :method => 'delete', :class => 'form-inline') do %>
         <div class="alert_message">You must confirm that you understand the consequences of your action!</div>
         <%= submit_tag('REMOVE ACCOUNT', :class => 'btn btn-default', :id => 'remove_account') %>
         <div class="checkbox">
           <label><%= check_box_tag('remove_account_confirm') %> I understand that all data will be lost</label>
         </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customers/show.html.erb
<div class="settings clearfix">
  <h1>Settings</h1>
  <div class="row">
    <div class="col-md-6 col-lg-3 col-lg-offset-2">
      <h2>BILLING ADDRESS</h2>
      <%= form_tag customer_path, method: :put do %>
	      <%= fields_for  :billing_address, @billing_address do |f| %>
	         <%= render partial: 'shared/errors', locals:{ entity: [@billing_address] }  %>
	         <%= render partial: 'order_steps/address_form', address: @billing_address, locals: {f: f}%>
	      <%end%>
         <%= submit_tag 'Save', class: 'btn btn-default' %>
      <%end%>
    </div>
    <div class="col-md-6 col-lg-3 col-lg-offset-2">
      <h2>SHIPPING ADDRESS</h2>
      <%= form_tag customer_path, method: :put do %>
	      <%= fields_for :shipping_address, @shipping_address do |f| %>
	         <%= render partial: 'shared/errors', locals:{ entity: [@shipping_address] }  %>
	         <%= render partial: 'order_steps/address_form', address: @shipping_address, locals: {f: f}%>
	      <%end%>
         <%= submit_tag 'Save', class: 'btn btn-default' %>
      <%end%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-lg-3 col-lg-offset-2">
      <h2>E-MAIL</h2>
      <%= form_tag(customer_path, :method => 'put') do %>
         <%= render partial: 'shared/errors', locals:{ entity: [@customer] }  %>
         <div class="form-group">
           <%= email_field_tag('email[email]', @customer.email, :class => 'form-control', :placeholder => 'Enter email')%>
         </div>
         <%= submit_tag('SAVE', :class => 'btn btn-default') %>
      <% end %>
    </div>
    <div class="col-md-6 col-lg-3 col-lg-offset-2">
      <h2>PASSWORD</h2>
      <%= form_tag(customer_path, :method => 'put', :autocomplete => 'off') do %>
         <%= render partial: 'shared/errors', locals:{ entity: [@customer] }  %>
         <div class="form-group">
           <%= label_tag('password[current_password]', 'Current password')%>
           <%= password_field_tag('password[current_password]', '', :class => 'form-control', :placeholder => 'Type current password') %>
         </div>
         <div class="form-group">
           <%= label_tag('password[password]', 'New password')%>
           <%= password_field_tag('password[password]', '', :class => 'form-control', :placeholder => 'Type new password') %>
         </div>
         <div class="form-group">
           <%= label_tag('password[password_confirmation]', 'New password confirmation')%>
           <%= password_field_tag('password[password_confirmation]', '', :class => 'form-control', :placeholder => 'Type new password confirmation') %>
         </div>
         <%= submit_tag('SAVE', :class => 'btn btn-default') %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-lg-offset-4">
      <h2>REMOVE ACCOUNT</h2>
      <%= form_tag(customer_path, :method => 'delete', :class => 'form-inline') do %>
         <div class="alert_message">You must confirm that you understand the consequences of your action!</div>
         <%= submit_tag('REMOVE ACCOUNT', :class => 'btn btn-default', :id => 'remove_account') %>
         <div class="checkbox">
           <label><%= check_box_tag('remove_account_confirm') %> I understand that all data will be lost</label>
         </div>
      <% end %>
    </div>
  </div>
</div>