config/routes.rb
Rails.application.routes.draw do

  mount ShopCart::Engine, at: '/cart', as: 'shop_cart'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks"}
  root 'books#home'
  resources :categories, only: [:show]
  resources :order_steps, only: [:show, :update]

  resources :books, only: [:index, :show] do
    get 'home',on: :collection
    resources :ratings, only: [:create, :new]
  end

  resource :customer, only: [:show,:update,:destroy]

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :customer
  belongs_to :book

  validates :review, :rating,:title, presence: true
  validates_inclusion_of :rating, :in => 1..10

  def self.get_rating id
    where(book_id: id)
  end


  def self.add_review (review,rating,title,customer_id,book_id)
    create!(review: review,
            rating: rating,
            title: title,
            customer_id: customer_id,
            book_id: book_id)
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  authorize_resource
  before_action :setter

  def new
  end

  def create
   @rating = @book.ratings.create(rating_params)
   @rating.customer_id = current_customer.id
     if @rating.save
      redirect_to book_path  params[:book_id] , flash[:success] =  'Review was successfully added! '
     else
       flash[:danger] =  'Review was not added! Please fill all fields!'
       render action: 'new'
     end
  end

  private

  def rating_params
    params.require(:ratings).permit(:rating,:title, :review)
  end

  def setter
    @book = Book.find_by_id params[:book_id]
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/new.html.erb
<div class="row">

  <h1>New review for <%= @book.title %> </h1>
     <%= form_tag(book_ratings_path) %>

        <%= text_field_tag 'ratings[title]',nil, cols:10, rows:10, class:"col-md-4 col-md-offset-4", placeholder: 'Enter title' %>

        <%= text_area_tag 'ratings[review]', nil, cols:10, rows:10, class:"col-md-4 col-md-offset-4", placeholder: 'Enter review' %>

        <%= number_field_tag "ratings[rating]",nil,in: 1..10, class:"col-md-1 col-md-offset-5", placeholder: 'Enter rating'%>

        <%= submit_tag "Submit", class: "btn btn-large btn-primary  col-md-4 col-md-offset-4" %>
</div>