config/routes.rb
Rails.application.routes.draw do

  mount ShopCart::Engine, at: '/cart', as: 'shop_cart'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks"}
  root 'books#home'
  resources :categories, only: [:show]
  resources :order_steps, only: [:show, :update]

  resources :books, only: [:index, :show] do
    get 'home',on: :collection
    resources :ratings, only: [:create, :new]
  end

  resource :customer, only: [:show,:update,:destroy]

end

app/models/book.rb
require 'carrierwave/orm/activerecord'

class Book < ActiveRecord::Base
  paginates_per 8
  belongs_to :author
  belongs_to :category
  has_many   :ratings

  validates  :title, :price, :quentity_books, presence: true

  mount_uploader :image, ImageUploader


  def self.by_category id
    where(category_id: id)
  end

  def self.bestsellers
    order('sold_count DESC').limit(5)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource


  def index
    @books = @books.page params[:page]
    @categories = Category.all
  end

  def show
    @ratings = @book.ratings
  end

  def home
      @bestsellers = Book.bestsellers
  end

end

app/helpers/books_helper.rb
module BooksHelper
  def add_to_cart(book,quantity)

  end
end

app/views/books/_body.html.erb
<% @books.each do |book|%>

   <div  class="col-xs-3 book">

     <div class="thumbnail">
       <%= link_to image_tag book.image_url(:thumb)%>
       <h5> <p class="title"><%= link_to book.title,  book_path(book)%></p></h5>
       <hr>
       <p class="price"><%=number_to_currency book.price%></p>
     </div>

   </div>

<% end %>
<div class="paginate">
  <%= paginate @books%>
</div>

app/views/books/_book.html.erb
<row>
<div class="container">

  <div class="full_image col-md-3">
    <%= image_tag @book.image_url%>
  </div>
<div class="col-md-4 ">

  <p class="title"><h3><%= @book.title%></h3></p>
  <p class="price"><h3><%=number_to_currency @book.price%></h3></p>
  <p class="date">Quentity Books: <%= @book.quentity_books%></p>
  <p class="date">Publication date: <%= @book.created_at.strftime("%d %B %Y")%></p>
  <p class="date"><h4>Description:</h4></br><%= @book.description%></p>
</div>

<div class="col-md-2">

  <%= form_tag(shop_cart.order_items_path,:method => 'post') do %>

     <%= number_field_tag 'orders[quantity]','1', in: 1..@book.quentity_books, class:'quantity-input'  %>

     <%= text_field_tag 'orders[book_id]' ,params[:id], style: 'visibility:hidden;'  %>

     <%= submit_tag "Add to Cart", class: "btn btn-large btn-primary" %>

  <% end %>

</div>





      </div>
    </div>

  </div>

</div>
</row>

app/views/books/home.html.erb
<div class="row">
  <div id="owl-carousel" class="owl-carousel owl-theme col-md-8 col-md-offset-2">
    <% @bestsellers.each do |book|%>
       <div class="item" style="text-align: center">
         <div class="clearfix">
           <h3 class="pull-left" ><%= book.title %></h3>
           <p>by <%= book.author.first_name  %> <%= book.author.last_name%></p>
         </div>
         <div class="row">
           <div class="col-md-6">
             <%= image_tag book.image_url, :class =>'pull-left img-thumbnail' %>
           </div>
           <div class="col-md-4">
             <%= book.description%>
             <%= form_tag(shop_cart.order_items_path,:method => 'post') do %>

                <%= number_field_tag 'orders[quantity]','1', in: 1..book.quentity_books, class:'quantity-input'  %>

                <%= text_field_tag 'orders[book_id]' ,book.id, style: 'visibility:hidden;'  %>

                <%= submit_tag "Add to Cart", class: "btn btn-large btn-primary" %>

             <% end %>
           </div>
         </div>



       </div>
    <% end %>
  </div>

</div>
<h3>Welcome to our amazing Bookstore!</br> Choose anything you wish, we'll ship it anywhere!</h3>

app/views/books/index.html.erb
<div class="main">

  <div class="container-fluid col-md-9 main-conteiner">

        <div class="row col-lg-9">
          <h1 class="page-header">Shop</h1>
          <%= render 'books/body'%>

        </div>

  </div>

  <%= render 'categories/sidebar'%>
</div>

app/views/books/show.html.erb
<%= render 'books/book'%>
<div class="container">

  <div class="col-md-12 col-lg-11 clearfix">
    <div class="thumbnail row">
     <ul class="nav nav-pills">
       <li><h4>Reviews</h4></li>
       <li><%= link_to "Add Review for this book", new_book_rating_path(book_id: params[:id]) %></li>
     </ul>

      <%@ratings.each  do |rating| %>
	      <ul class="nav nav-pills" >
	        <hr>
	        <div>
	          <% (1..10).each do |rating_number|%>
	           <% if rating_number <= rating.rating%>
		          <i class="fa fa-star fa-2x" style="color: rgb(255,215,0)"></i>
			          <% else %>
		          <i class="fa fa-star-o fa-2x"></i>
			          <% end %>
	          <% end %>
	          <%= rating.title%>
	          <%= rating.created_at.strftime("%d %B %Y")%>
	        </div>
	        <li> by: <%= rating.customer.first_name%> <%=rating.customer.last_name%></li></br>
	        <li> review: <%= rating.review%></li>
	      </ul>

      <% end %>
    </div>
  </div>
</div>