config/routes.rb
Rails.application.routes.draw do

  mount ShopCart::Engine, at: '/cart', as: 'shop_cart'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks"}
  root 'books#home'
  resources :categories, only: [:show]
  resources :order_steps, only: [:show, :update]

  resources :books, only: [:index, :show] do
    get 'home',on: :collection
    resources :ratings, only: [:create, :new]
  end

  resource :customer, only: [:show,:update,:destroy]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(customer)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities


    #customer ||= Customer.new
  if customer
    if customer.admin?
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard
      can :manage, :all
    else
      #can [:index,:destroy,:create,:update,:destroy_all], OrderItem
      can [:create, :new],Rating,customer:customer
      can [:index,:show,:home],Book
      can :show,Category
      can :read,DeliveryMethod,customer:customer
      can [:read,:create,:update],Address,customer:customer
      can [:read,:create,:update],CreditCard,customer:customer
      can [:destroy,:show,:update],Customer, customer:customer
      can [:show,:index,:update],ShopCart::Order, customer:customer

    end
  else
    can [:index,:show,:home], Book
    can :show, Category
  end


  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  validates  :address,:first_name,:last_name, :city, :phone, :country,:zipcode,  presence: true
  #validates  :zipcode, format: { with: /[0-9]{5}/ }, presence: true
  belongs_to :country
  belongs_to :customer
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many  :books
  validates :first_name, :last_name, presence: true
end

app/models/book.rb
require 'carrierwave/orm/activerecord'

class Book < ActiveRecord::Base
  paginates_per 8
  belongs_to :author
  belongs_to :category
  has_many   :ratings

  validates  :title, :price, :quentity_books, presence: true

  mount_uploader :image, ImageUploader


  def self.by_category id
    where(category_id: id)
  end

  def self.bestsellers
    order('sold_count DESC').limit(5)
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many  :books

  validates :title, presence: true
  validates :title, uniqueness: { case_sensitive: false }
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :addresses

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
  #belongs_to :customer
  has_many :orders, class_name: 'ShopCart::Order'


  validates  :number, :CVV, :expiration_month, :expiration_year,  presence: true
=begin
  validates :legacy_code, format: { with: /\A[a-zA-Z]+\z/,
                                    message: "only allows letters" }
=end
  validates :number, format: { with: /[0-9]{4}\-[0-9]{4}\-[0-9]{4}\-[0-9]{4}/,
                   message:  "format should be like '1234-1234-1234-1234'"}, presence: true
  validates :CVV, format: { with: /[0-9]{3}/,
                message:  "should be like '123' "}, presence: true


  def display_number
    '****-****-****-'+number.to_s.slice(-4..-1)
  end

  def display_month
    expiration_month.to_s.rjust(2, '0')
  end

  def month_list
    (1..12).map{|month| [month.to_s.rjust(2, '0'), month]}
  end

  def year_list
    first_year = Time.zone.now.year
    last_year = first_year+7
    (first_year..last_year).map{|year| [year, year]}
  end


end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
 include AddressSaver

  has_many  :orders, class_name: 'ShopCart::Order'
  has_many  :ratings
  has_many  :addresses
 # has_many  :credit_cards

  belongs_to :billing_address, class_name: "Address"
  belongs_to :shipping_address, class_name: "Address"


  validates :email,presence: true
  validates :email, uniqueness: { case_sensitive: false }


  def admin?
    self.admin
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |customer|
      customer.email = auth.info.email
      customer.password = Devise.friendly_token[0, 20]
      customer.first_name = auth.info.first_name
      customer.last_name = auth.info.last_name
      customer.provider = auth.provider
      customer.uid = auth.uid
    end
  end

  def order_in_progress
    self.orders.find_or_create_by(state: 'in progress')
  end

  def last_orders
    self.orders.already_completed.order(state: :asc, completed_date: :desc).first
  end

  def all_orders
    self.orders.already_completed.order(state: :asc, completed_date: :desc)
  end

end

app/models/delivery_method.rb
class DeliveryMethod < ActiveRecord::Base
  STATE = %w(inactive, active)
  validates :name, :price,:state, presence: true
  validates :name, uniqueness: true


  enum state: STATE
  scope :active, -> {where state: 1}
  def state_enum
    STATE
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :customer
  belongs_to :book

  validates :review, :rating,:title, presence: true
  validates_inclusion_of :rating, :in => 1..10

  def self.get_rating id
    where(book_id: id)
  end


  def self.add_review (review,rating,title,customer_id,book_id)
    create!(review: review,
            rating: rating,
            title: title,
            customer_id: customer_id,
            book_id: book_id)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource


  def index
    @books = @books.page params[:page]
    @categories = Category.all
  end

  def show
    @ratings = @book.ratings
  end

  def home
      @bestsellers = Book.bestsellers
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def add_to_cart(book,quantity)

  end
end

app/helpers/carousels_helper.rb
module CarouselsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper

end

app/helpers/order_steps_helper.rb
module OrderStepsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#b-menu-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">The Bookstore</a>
    </div>
    <div class="collapse navbar-collapse" id="b-menu-1">
      <ul class="nav navbar-nav navbar-right">
        <li ><%= link_to "HOME",    main_app.root_path %></li>
        <li ><%= link_to "SHOP",    main_app.books_path %></li>
        <li style="padding-top: 15px;">
        <% if customer_signed_in? %>

             <i class="glyphicon glyphicon-shopping-cart">
               <%= link_to_unless_current('CART', shop_cart.order_items_path) %>:
               <%  if (current_customer_order.nil? || current_customer_order.total_items == 0) %>
                  <%= '(EMPTY)' %>
               <% else %>
                  <%= "(#{current_customer_order.total_items}) #{number_to_currency(current_customer_order.total_price)}" %>
               <%end%>
             </i>

        <% end %>
        </li>

        <% if customer_signed_in? %>
           <% if current_customer.admin?%>
              <li><%= link_to "Admin Dashboard", main_app.rails_admin_path %></li>
           <% end %>
           <li><%= link_to "Settings",    main_app.customer_path %></li>
           <li><%= link_to "Orders",    shop_cart.orders_path %></li>
           <li><%= link_to "Sign out", main_app.destroy_customer_session_path, :method => :delete %></li>
        <%else%>
           <li><%= link_to "Sign in",    main_app.new_customer_session_path %></li>
           <li><%= link_to "Sign up",    main_app.new_customer_registration_path %></li>
        <%end%>


      </ul>
    </div> <!-- /.nav-collapse -->
  </div> <!-- /.container -->
</div> <!-- /.navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,600,300,200&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header'%>
<% flash.each do |key, value| %>
   <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>


  <%= yield %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_errors.html.erb
<div class="text_align_center font_opensans">
     <% entity.each do |e| %>
      <% if e.errors.any? %>
<div id="error_explanation">
     <div class="alert alert-error">
    The form contains <%= pluralize(e.errors.count, "error") %>.
            </div>
            <ul>
              <% e.errors.full_messages.each do |msg| %>
                  <li>* <%= msg %></li>
              <% end %>
            </ul>
</div>
      <% end %>
  <% end %>
</div>